service: product-service

frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: 'npm'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  httpApi:
    cors: true
  lambdaHashingVersion: '20201221'

functions:
  createProduct:
    handler: handler.createNewProduct
    events:
      - httpApi:
          path: /products
          method: post
  getProductsById:
    handler: handler.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: /products
          method: get